### ISSUE TITLE
config backgroudColor for dmg 

### ISSUE THREAD

**Issue by git-boya** [leanflutter/flutter_distributor#115]
配置了backgroundColor 无效;
```
title: 小工具
backgroundColor: #604878
window:
  - size:
    - width: 500
    - height: 400
contents:
  - x: 192
    y: 344
    type: file
    path: 小工具.app
  - x: 448
    y: 344
    type: link
    path: "/Applications"
```
看 appdmg 说明里参数名叫background-color, 是不是映射不过去?
