### ISSUE TITLE
AppImage file not found on release

### ISSUE THREAD

**Issue by enoy19** [leanflutter/flutter_distributor#118]
The tool tries to publish the application bundle/artifact with a `.appimage` extension. The Bundle packaged with `.AppImage` - case sensitive.

A work around is calling the package command for `--target appimage` and then publishing it "manually" with the `publish` command and providing the correct path: `--path='dist/myapp-1.0.0+1-linux.AppImage'`

**Comment by lijy91** [comment]
Please check your dist directory to find the correct path

**Comment by enoy19** [comment]
Dear @lijy91,

The dist folder exists.
The AppImage also exists.

Let me give you more context.
`distribute_options.yaml`:
```
output: dist/
releases:
  - name: release
    jobs:
      - name: linux-appimage
        package:
          platform: linux
          target: appimage
        publish:
          target: github
          args:
            repo-owner: the-owner
            repo-name: the-repo
```

when I call `flutter_distributor publish` the flutter_distributor start building and packaging the AppImage correctly and places it in the `dist` folder.
Then, when it comes to uploading the AppImage to GitHub, it tries to upload the file `myapp-1.0.0+1-linux.appimage` instead of `myapp-1.0.0+1-linux.AppImage`. Please note that I wrote `appimage` with a **lower cased 'a'** and a **lower cased 'i'**.
Therefore, the publish part is not able to find the `AppImage` artifact on case sensitive file systems and fails because it could not find the file.

This bug most likely does not appear on Windows, because it may ignore the capital and lowercased letters.
