### ISSUE TITLE
Bad state: No element

### ISSUE THREAD

**Issue by whiteLT** [leanflutter/flutter_distributor#134]
Application is compiled successfully but unable to proceed with uploading
![image](https://github.com/leanflutter/flutter_distributor/assets/8414354/dfeaf986-df9c-46e1-9442-6b0a57881347)

```
variables:
  # See: https://appcenter.ms/settings/apitokens
  APPCENTER_API_TOKEN: "..."
output: dist/
releases:
  - name: azdev
    jobs:
      - name: release-azdev-android
        package:
          platform: android
          target: apk
          build_args:
            flavor: azdevappCenter
            target: lib/main_azdev.dart
        # Publish to appcenter
        publish:
          target: appcenter
          args:
            owner-name: "..."
            app-name: "...."
            distribution-group: "..."
```

Full error:

```
Bad state: No element
#0      List.first (dart:core-patch/growable_array.dart:343:5)
#1      AppPackageMakerApk.make (package:flutter_app_packager/src/makers/apk/app_package_maker_apk.dart:13:29)
#2      FlutterAppPackager.package (package:flutter_app_packager/src/flutter_app_packager.dart:40:18)
#3      FlutterDistributor.package (package:flutter_distributor/src/flutter_distributor.dart:182:51)
<asynchronous suspension>
#4      FlutterDistributor.release (package:flutter_distributor/src/flutter_distributor.dart:327:45)
<asynchronous suspension>
#5      CommandRunner.runCommand (package:args/command_runner.dart:212:13)
<asynchronous suspension>
```
