### ISSUE TITLE
Multiple jobs with same platform and target

### ISSUE THREAD

**Issue by problematicconsumer** [leanflutter/flutter_distributor#135]
How can I have two or more jobs (on same release) with same target and platform but different args, etc?

Example use case: building both bundle and split APKs for android.

```yaml
releases:
  - name: prod
    jobs:
      - name: release-android-bundle
        package:
          platform: android
          target: apk
          build_args:
            target-platform: android-arm,android-arm64,android-x64
      - name: release-android-apk
        package:
          platform: android
          target: apk
          build_args:
            split-per-abi: ''
            target-platform: android-arm,android-arm64,android-x64
```
