### ISSUE TITLE
Error when packing DEB package: end of file before value of field 'Uploaders' (missing final newline)

### ISSUE THREAD

**Issue by Muska-Ami** [leanflutter/flutter_distributor#155]
Logs:
https://github.com/Muska-Ami/NyaLCF/actions/runs/7327471300/job/19954421475

Idnt sure if it's missing configurations in my `make_config.yaml`, I have compare it with the doc, and seem it doesn't have any options missed?

My `make_config.yaml` :
```yml
display_name: Nya LoCyanFrp!
package_name: nyanana
maintainer:
  name: Muska-Ami
  email: xmcn@1l1.icu
co_authors: []
priority: optional
section: x11
installed_size: 6604
essential: false
icon: asset/icon/icon.png

postinstall_scripts: []
postuninstall_scripts: []
keywords:
  - NyaLCF
  - Nya LoCyanFrp!
  - nyanana
  - LoCyanFrp

generic_name: NyaLCF

categories:
  - Network

startup_notify: true
```
