### ISSUE TITLE
Why does it seem like it doesn't support environment variables

### ISSUE THREAD

**Issue by chinghoi** [leanflutter/flutter_distributor#163]
I don't know what else needs to be configured
```
variables:
  PGYER_API_KEY: $PGYER_API_KEY
```
In terminal `$PGYER_API_KEY` is effective, like
<img width="534" alt="image" src="https://github.com/leanflutter/flutter_distributor/assets/20352401/0c531b95-b614-4be2-9f2d-b6f4f27df617">
but
<img width="981" alt="image" src="https://github.com/leanflutter/flutter_distributor/assets/20352401/4f312651-4aec-4ec1-8569-74ce94721d03">

**Comment by ddikman** [comment]
@chinghoi although it won't allow you to reference variables inside the variables array, looking at this code:
https://github.com/leanflutter/flutter_distributor/blob/main/packages/flutter_distributor/lib/src/flutter_distributor.dart#L325

It looks as though it will be pulling in the platform variables so if you just remove that one variable, it should work anyway.

However, I see in some places like here:
https://github.com/leanflutter/flutter_distributor/blob/main/packages/flutter_distributor/lib/src/flutter_distributor.dart#L156

That they might get included only as a fallback, so if just removing it doesn't work perhaps there is a bug.

**Comment by cybrox** [comment]
It will definitely pull platform variables. I've been using this config for a long time now:

```yaml
#distribute_options.yaml
env:
  # GOOGLE_APPLICATION_CREDENTIALS is exported by ./.keys/android/register.sh
  # APPSTORE_USERNAME and APPSTORE_PASSWORD is exported by ./.keys/ios/register.sh

releases:
```
# Makefile
ios_release:
	source .keys/ios/register.sh && \
	flutter_distributor release --name ios --jobs ios-production
```

```
