### ISSUE TITLE
type 'Null' is not a subtype of type 'Map<String, dynamic>'

### ISSUE THREAD

**Issue by iBog** [leanflutter/flutter_distributor#173]
flutter_distributor package --platform macos --targets dmg

type 'Null' is not a subtype of type 'Map<String, dynamic>'
#0      FlutterDistributor.distributeOptions (package:flutter_distributor/src/flutter_distributor.dart:66:16)
#1      FlutterDistributor.package (package:flutter_distributor/src/flutter_distributor.dart:138:35)
#2      CommandPackage.run (file:///Users/user/.pub-cache/hosted/pub.dev/flutter_distributor-0.3.7/bin/command_package.dart:132:24)
#3      CommandRunner.runCommand (package:args/command_runner.dart:212:27)
#4      main (file:///Users/user/.pub-cache/hosted/pub.dev/flutter_distributor-0.3.7/bin/main.dart:47:17)
<asynchronous suspension>

**Comment by cybrox** [comment]
What's your `distribute_options.yml`?

**Comment by iBog** [comment]
> What's your `distribute_options.yaml`?

it's exists but empty, i have no plans distribute anything, want to create 'dmg' file only

**Comment by lijy91** [comment]
You need to create a job to package dmg

```yaml
output: dist/
releases:
  - name: dev
    jobs:
      - name: release-dmg
        package:
          platform: macos
          target: dmg
          build_args:
            dart-define:
              APP_ENV: dev
```
