### ISSUE TITLE
Q: Does it obfuscate the code?

### ISSUE THREAD

**Issue by maxfornacon** [leanflutter/flutter_distributor#180]
Does flutter_distributor obfuscate the code? 

I suppose not, as far as I have seen it in the logs. Would it be possible somehow to add the --obfuscate flag to the build command? 

https://docs.flutter.dev/deployment/obfuscate

**Comment by lijy91** [comment]
You can add any arguments supported by the flutter build command.

```
releases:
  - name: prod
    jobs:
      - name: apk
        package:
          platform: android
          target: apk
          build_args:
            obfuscate: true
```
