### ISSUE TITLE
package config background invalid

### ISSUE THREAD

**Issue by anniso** [leanflutter/flutter_distributor#240]
```
title: Myapp
background: "../../assets/images/dmgInstall.png"
contents:
  - x: 480
    y: 250
    type: link
    path: "/Applications"
  - x: 180
    y: 250
    type: file
    path: Myapp.app
```

```
[ 1/21] Looking for target...                
[ OK ]
[ 2/21] Reading JSON Specification...        
[ OK ]
[ 3/21] Parsing JSON Specification...        
[ OK ]
[ 4/21] Validating JSON Specification...     [ OK ]
[ 5/21] Looking for files...                 
[ OK ]
[ 6/21] Calculating size of image...         
[ OK ]
[ 7/21] Creating temporary image...          
[ OK ]
[ 8/21] Mounting temporary image...          
[ OK ]
[ 9/21] Making hidden background folder...   [ OK ]
[10/21] Copying background...                
[ OK ]
[11/21] Reading background dimensions...     
[ OK ]
[12/21] Copying icon...                      
[SKIP]
[13/21] Setting icon...                      [SKIP]
[14/21] Creating links...                    
[ OK ]
[15/21] Copying files...                     
[ OK ]
[16/21] Making all the visuals...            
[ OK ]
[17/21] Blessing image...                    
[ OK ]
[18/21] Unmounting temporary image...        
[ OK ]
[19/21] Finalizing image...                  
[ OK ]
[20/21] Signing image...                     [SKIP]
[21/21] Removing temporary image...          
[ OK ]
[22/21] Removing target image...             [ OK ]

Your image is ready:
```

Unable to display background properly, but PNG file can be seen in dmg-.background
