### ISSUE TITLE
It is recommended to add custom appName for package exe

### ISSUE THREAD

**Issue by csj8520** [leanflutter/flutter_distributor#25]
Recommended in
windows\packaging\exe\make_ config. yaml
Add custom appName

**Comment by lijy91** [comment]
Supported, will be released in the next version, supports custom display name and installation directory name

```yaml
app_id: C52EDEB4-E345-4C95-BF90-E2BF83CF2B30
publisher_name: LeanFlutter
publisher_url: https://github.com/leanflutter/flutter_distributor
display_name: Hello World
create_desktop_icon: true
install_dir_name: HELLO-WORLD
locales:
  - zh
```
