### ISSUE TITLE
XCode打包怎么新增-allowProvisioningUpdates参数

### ISSUE THREAD

**Issue by SheepYang1993** [leanflutter/flutter_distributor#255]
用GithubActions打包时报错，提示：
Failed to build iOS app
Error (Xcode): No profiles for 'com.xxx.xxx' were found: Xcode couldn't find any iOS App Development provisioning profiles matching 'com.xxx.xxx'. Automatic signing is disabled and unable to generate a profile. To enable automatic signing, pass -allowProvisioningUpdates to xcodebuild.

**Comment by SheepYang1993** [comment]
这是workflow的yml文件
```
name: BuildIpa
on: # 触发条件
  push:
    branches: [deploy-ipa-appstore]
jobs:
  build:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: "recursive" # 拉取所有子模块
          fetch-depth: 0 # 拉取完整的提交历史，确保子模块的正确性
          token: ${{ secrets.PRIVATE_REPO_TOKEN }} # 使用 PAT 访问私有子模块
      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: "stable"
          flutter-version: "3.22.3"
      - name: Build Prod IPA To AppStore
        run: |
          flutter pub get
          dart pub global activate flutter_distributor
          flutter_distributor release --name ipa-prod-appstore

```

**Comment by SheepYang1993** [comment]
这是`distribute_options.yaml`
```
variables:
  PGYER_API_KEY: "xxxx"
  APPSTORE_USERNAME: "xxx"
  APPSTORE_PASSWORD: "xxx"
output: dist/
releases:
  - name: ipa-prod-appstore
    jobs:
      # 构建 prod ipa 包并将其发布到 appstore
      - name: release-prod-ios
        package:
          platform: ios
          target: ipa
          build_args:
            dart-define:
              APP_ENV: prod
              APP_CHANNEL: Appstore
            export-options-plist: ios/prod_ExportOptions.plist
        publish_to: appstore
```
