### ISSUE TITLE
windows下使用script_template会导致locale无效

### ISSUE THREAD

**Issue by anniso** [leanflutter/flutter_distributor#258]
生成的iss文件languages为空
```
locales:
  - lang: zh
    file: ..\ChineseSimplified.isl
  - lang: en
script_template: inno_setup.iss
```
