### ISSUE TITLE
Windows installation package configuration

### ISSUE THREAD

**Issue by yh4922** [leanflutter/flutter_distributor#39]
Package the exe installation package, hoping to support the configuration of the installation interface language, custom shortcut names, and some other configurations

**Comment by lijy91** [comment]
Supported, will be released in the next version, supports custom display name and installation directory name

```yaml
app_id: C52EDEB4-E345-4C95-BF90-E2BF83CF2B30
publisher_name: LeanFlutter
publisher_url: https://github.com/leanflutter/flutter_distributor
display_name: Hello World
create_desktop_icon: true
install_dir_name: HELLO-WORLD
locales:
  - zh
```
