### ISSUE TITLE
【Windows】自定义应用名、默认选中创建桌面快捷方式

### ISSUE THREAD

**Issue by 15563988825** [leanflutter/flutter_distributor#57]
是否可添加功能
make_config.yaml中是否可添加配置项
1、Windows中是否可添加appName设置
     `控制iss文件中的：#define MyAppName "XXXX"`
2、添加是否默认选中“创建桌面快捷方式”，配置项目
   ```
控制iss文件中的 [Tasks] 节点下的
Name: "desktopicon"; Description: "{cm:CreateDesktopIcon}"; GroupDescription: "{cm:AdditionalIcons}"
默认check值
```

**Comment by lijy91** [comment]
1. 计划增加 `display_name` 字段用于自定义应用名称（安装目录暂时计划保持为项目名）

```yaml
display_name: MyAppName
```

2. 计划增加 `create_desktop_icon` 字段用于是否默认创建桌面图标
```yaml
create_desktop_icon: true
```

**Comment by 15563988825** [comment]
Bingo！
Expecting...

**Comment by 15563988825** [comment]
您好，我创建了一个新的PR
https://github.com/leanflutter/flutter_distributor/pull/58
新增了exe打包时，以下几个扩展参数

1. appDisplayName--可替代默认appName(应用名,暂不支持中文)
2. appExeFileName--可替代默认可执行程序名(如:hello_world.exe)
3. defaultDesktopIconCkecked--可配置是否默认勾选“创建桌面快捷方式”默认为不勾选
4. innoSetupDir--可动态配置InnoSetup的安装路径，默认为C:\Program Files (x86)\Inno Setup 6

**Comment by lijy91** [comment]
已增加显示名称，安装目录名称，创建桌面图标，语言等选项，将在下一版本中发布

```yaml
app_id: C52EDEB4-E345-4C95-BF90-E2BF83CF2B30
publisher_name: LeanFlutter
publisher_url: https://github.com/leanflutter/flutter_distributor
display_name: Hello World
create_desktop_icon: true
install_dir_name: HELLO-WORLD
locales:
  - zh
```
