### ISSUE TITLE
能否加个功能运行自定义脚本

### ISSUE THREAD

**Issue by JerryFans** [leanflutter/flutter_distributor#59]
能否加个功能 build success 先别 转成相应dmg ， 加个参数 先运行下 custom_script，再封装包。

**Comment by lijy91** [comment]
考虑在 job 中增加 scripts 节点，目前参考 npm 的 scripts 逻辑，计划加入 prepare, prepackage, postpackage。
```yaml
output: dist/
releases:
  - name: dev
    jobs:
      - name: release-dev-macos
        scripts:
          - prepare: "./prepare.sh"
            prepackage: "./prepackage.sh"
            postpackage: "./postpackage.sh"
        package:
          platform: macos
          target: apk
          build_args:
            target-platform: android-arm,android-arm64
            dart-define:
              APP_ENV: dev
```
