### ISSUE TITLE
Support custom `artifact_name` and `channel` parameter in package command.

### ISSUE THREAD

**Issue by lijy91** [leanflutter/flutter_distributor#60]
My solution is to provide custom artifact_name and add arch parameter in package command.

```yaml
output: dist/
artifact_name: "{{name}}{{#channel}}-{{channel}}{{/channel}}-{{version}}}-{{platform}}.{{ext}}"
releases:
  - name: release
    jobs:
      - name: arm32
        package:
          platform: android
          target: apk
          build_args:
            target-platform: android-arm
      - name: arm64
        package:
          platform: android
          arch: arm64
          target: apk
          build_args:
            target-platform: android-arm64
```

_Originally posted by @lijy91 in https://github.com/leanflutter/flutter_distributor/issues/53#issuecomment-1077448501_
