### ISSUE TITLE
打包exe安装包配置 display_name 不生效

### ISSUE THREAD

**Issue by yh4922** [leanflutter/flutter_distributor#71]
打包之后安装包名称`sdc_plus_plus-1.1.1+1.1.1-windows-setup.exe`，安装完成后立即执行提示
![image](https://user-images.githubusercontent.com/18353610/168243300-0377dba8-b3a5-46a5-b903-e22e589901ab.png)

桌面的快捷方式还是`sdc_plus_plus`，运行提示找不到文件
![image](https://user-images.githubusercontent.com/18353610/168243462-53a74246-2c1c-4a93-aaf2-d974b2c668b2.png)

make_config.yaml
```yaml
app_id: xxxxxx
publisher_name: Yohann
display_name: SDC++
executable_name: SDC++.exe
create_desktop_icon: true
install_dir_name: SDC++
locales:
  - zh
```

pubspec.yaml
```yaml
name: sdc_plus_plus
version: 1.1.1
```

flutter_distributor --version
```
$ flutter_distributor --version                               
0.2.2
```

flutter doctor
```
$ flutter doctor
Flutter assets will be downloaded from https://storage.flutter-io.cn. Make sure you trust this source!
Doctor summary (to see all details, run flutter doctor -v):
[√] Flutter (Channel stable, 2.10.1, on Microsoft Windows [Version 10.0.19044.1526], locale zh-CN)
[√] Android toolchain - develop for Android devices (Android SDK version 32.1.0-rc1)
[√] Chrome - develop for the web
[√] Visual Studio - develop for Windows (Visual Studio 生成工具 2019 16.11.9)       
[√] Android Studio (version 4.2)
[√] VS Code (version 1.66.2)
[!] Proxy Configuration
    ! NO_PROXY is not set
[√] Connected device (3 available)
    ! Device 192.168.18.66:5555 is offline.
[√] HTTP Host Availability

! Doctor found issues in 1 category.
```
