### ISSUE TITLE
是否支持同时发布至多个pgy账户

### ISSUE THREAD

**Issue by weiwill** [leanflutter/flutter_distributor#73]
<img width="674" alt="image" src="https://user-images.githubusercontent.com/3794090/169735411-6c899854-ebd0-4491-b3b1-fad5099429e6.png">
现在PGYER_API_KEY是写在最上层的，是不是意思是多个release name只能发布到同一个蒲公英账户下面
如果想不同的job发不到不同的蒲公英账户下面，现在是不是还不支持？

**Comment by lijy91** [comment]
初步构思，增加 publishers 字段，可以配置多个发布器

```yaml
env:
  FIREBASE_TOKEN: your token, See[https://firebase.google.com/docs/cli?authuser=0#cli-ci-systems]
output: dist/
publishers:
  - name: pgyer-1
    env:
      PGYER_API_KEY: 'your api key'
  - name: pgyer-2
    env:
      PGYER_API_KEY: 'your api key'
releases:
  - name: dev
    jobs:
      - name: release-dev-android
        package:
          platform: android
          target: apk
          build_args:
            target-platform: android-arm
        publish_to: pgyer-1
  - name: prod
    jobs:
      - name: release-prod-android
        package:
          platform: android
          target: apk
          build_args:
            target-platform: android-arm
        publish_to: pgyer-2
```

**Comment by lijy91** [comment]
请更新到 0.3.4 版本，这个版本支持给 job 定义环境变量，你可以为每个 job 设置不同的 apikey

```yaml
output: dist/
releases:
  - name: dev-release
    jobs:
      - name: android-apk1
         variables:
           PGYER_API_KEY: 'your api key'
        package:
          platform: android
          target: apk
          build_args:
            target-platform: android-arm,android-arm64
      - name: android-apk2
         variables:
           PGYER_API_KEY: 'your api key'
        package:
          platform: android
          target: apk
          build_args:
            target-platform: android-arm,android-arm64
```
