### ISSUE TITLE
How to set build args split-per-abi 

### ISSUE THREAD

**Issue by Adherentman** [leanflutter/flutter_distributor#86]
When packaging, for the size of the package, I used `flutter build apk --split-per-abi`, how to set this parameter in yaml

**Comment by lijy91** [comment]
you can try like this

```yaml
releases:
  - name: release-android
    jobs:
      - name: release-android-dev
        package:
          platform: android
          target: apk
          channel: dev2
          build_args:
            split-per-abi: ''
            flavor: dev
            dart-define:
              APP_ENV: dev
```
